fields:
  - name: pro_com
    type: integer
    description: Codice numerico del Comune ISTAT (2021)
  - name: comune
    type: string
    description: Denominazione del Comune
  - name: zona
    type: string
    description: Tipologia di restrizioni applicate
  - name: data_inizio
    type: date
    description: Data di inizio delle restrizioni
  - name: data_fine
    type: date
    description: Data di fine delle restrizioni
  - name: id_ordinanza
    type: string
    description: Codice identificativo dell'ordinanza della Presidenza della Regione Siciliana. Indica il numero e la data dell'ordinanza nel formato DDMMYYYY
  - name: nro_ordinanza
    type: integer
    description: Numero dell'ordinanza della Presidenza della Regione Siciliana
  - name: data_ordinanza
    type: date
    description: Data dell'ordinanza della Presidenza della Regione Siciliana
  - name: PDF
    type: string
    description: Accessibilità dei file PDF
  - name: nro_pgg
    type: integer
    description: Numero di pagine dell'ordinanza
  - name: link_ordinanza
    type: string
    description: URL ordinanza della Presidenza della Regione Siciliana
  - name: note
    type: string
    description: Eventuali annotazioni
