name: Update CSV

on:
  schedule:
    - cron: '0 0 * * 7'
  workflow_dispatch:

jobs:
  check_new:
    runs-on: ubuntu-latest
    steps:
      
      - name: Git checkout
        uses: actions/checkout@v2
      
      - name: Update CSV data
        run: |
          curl "https://docs.google.com/spreadsheets/d/e/2PACX-1vSA38rXb3R9B0lYUtHvgvr9aWcxwiYAxksTTAg-jIbe1qjGh2bGANgUlUnuynG-UL6U2iLY7rgPvuOH/pub?gid=1759652035&single=true&output=csv" > ordinanze_covid_sicilia.csv
          echo "Dati aggiornati!"

      - name: Update Repository
        run: |-
          git config user.name "autoupdate"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date --iso-8601=seconds)
          git commit -m "update: ${timestamp}" || exit 0
          git push
