name: Update CSV

on:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:
  push:
        
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: Installing csvkit
        run: |-
          pip install csvkit
        
      - name: Update CSV data
        run: |
          curl -kL "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjsfEfBUYtVaHt1V8LCBPeviNCG2NqQ2I3F9z21hKpFUYPcg0NewuJybXmpU2FWnR4jDKnrpzorAAK/pub?gid=827808262&single=true&output=csv" > data.csv
          echo "Dati aggiornati!"

      - name: Build JSON
        run: |
          csvjson data.csv > data.json
          echo "JSON creato!"

      - name: Update Repository
        run: |-
          git config user.name "autoupdate"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date --iso-8601=seconds)
          git commit -m "update: ${timestamp}" || exit 0
          git push
